name: Check twitter for loadshedding

on:
  workflow_dispatch:
  schedule:
    # Jobs can run at most every 5 minutes
    # https://github.blog/changelog/2019-11-01-github-actions-scheduled-jobs-maximum-frequency-is-changing/
    - cron: '*/5 * * * *'


jobs:
  check-coct-twitter:
    runs-on: ubuntu-latest
    environment: auto-pr-env
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install requests pyyaml

    - name: Run python script
      run: python3 src/auto_pull_request.py
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
