name: Build Calendars

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manually_specified.yaml'

jobs:
  build-calendars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt
    - name: Run
      run: cargo run
    - uses: meeDamian/github-release@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.0
        name: Latest Eskom Loadshedding Calendars
        body: |
          To get your loadshedding schedule in your calendar:
          
          1) scroll down to the blue links under `Assets`. 
          2) Find the `ics` calendar file corresponding to your area.
          3) Right-click on the file and copy the link.
          4) Open your calendar app (Google Calendar, Outlook, 
          or Apple Calendar).
          5) Paste the calendar link in your app's `subscribe to calendar`
          option.
          
          That's it! Now you've got loadshedding warning in your 
          calendar that  tell you if the power will be off or not. 
          This is better
          than apps like EskomSePush because it combines what area
          you're in with your area's loadshedding schedule. So you'll
          only be notified if 1) there's national loadshedding announced
          by Eskom and 2) your area has loadshedding scheduled for
          that time.
          
          It's also open source! We depend on pull requests to update
          `manually_specified.yaml` with the latest schedule. Please
          submit a PR if Eskom announces a change!
          
        gzip: false
        allow_override: true
        files: >
          calendars/Albertinia.ics
          calendars/Arniston.ics
          calendars/Beaufort-West.ics
          calendars/Betties-Bay.ics
          calendars/Botrivier.ics
          calendars/Bredasdorp.ics
          calendars/Caledon.ics
          calendars/Calitzdorp.ics
          calendars/Ceres.ics
          calendars/Citrusdal.ics
          calendars/Clanwilliam.ics
          calendars/Darling.ics
          calendars/De-Doorns.ics
          calendars/DeRust.ics
          calendars/Dysselsdorp.ics
          calendars/Elandsbaai.ics
          calendars/Franschoek.ics
          calendars/Gansbaai.ics
          calendars/Genadendal.ics
          calendars/George.ics
          calendars/Glentana.ics
          calendars/Goedverwacht.ics
          calendars/Gouda.ics
          calendars/Graaf-water.ics
          calendars/Grabouw.ics
          calendars/Greyton.ics
          calendars/Grootbrak.ics
          calendars/Hawston.ics
          calendars/Heidelburg.ics
          calendars/Herbetsdal.ics
          calendars/Hermanus.ics
          calendars/Hopeful.ics
          calendars/Infanta.ics
          calendars/Klawer.ics
          calendars/Kleinbrak.ics
          calendars/Kleinmond.ics
          calendars/Klipdale.ics
          calendars/Knysna.ics
          calendars/Ladismith.ics
          calendars/Laingsburg.ics
          calendars/Lambertsbaai.ics
          calendars/Langebaan.ics
          calendars/Lutzville.ics
          calendars/Malgas.ics
          calendars/Malmesbury.ics
          calendars/Moorreesbury.ics
          calendars/Mossel-Bay.ics
          calendars/Napier.ics
          calendars/Oudtshoorn.ics
          calendars/Paternoster.ics
          calendars/Piketberg.ics
          calendars/Plettenberg-Bay.ics
          calendars/Porterville.ics
          calendars/PrinceAlbertTown.ics
          calendars/Pringle-Bay.ics
          calendars/Protem.ics
          calendars/Rheenendal.ics
          calendars/Riebeeck-Kasteel.ics
          calendars/Riebeeck-West.ics
          calendars/Riversdale.ics
          calendars/Riviersonderend.ics
          calendars/SaldanahBay.ics
          calendars/StHelenaBay.ics
          calendars/Stanford.ics
          calendars/Stellenbosch.ics
          calendars/Stompeus-Bay.ics
          calendars/Struisbaai.ics
          calendars/Sutherland.ics
          calendars/Suurbraak.ics
          calendars/Swellendam.ics
          calendars/Tesselaarsdal.ics
          calendars/Touwsrivier.ics
          calendars/Tulbagh.ics
          calendars/Van-Rhynsdorp.ics
          calendars/Vanwyksdorp.ics
          calendars/Velddrift.ics
          calendars/Villiersdorp.ics
          calendars/Vleesbaai.ics
          calendars/Vredenburg.ics
          calendars/Vredendal.ics
          calendars/Wellington.ics
          calendars/Witsand.ics
          calendars/Wolseley.ics
          calendars/Worscester.ics
          calendars/Yzerfontein.ics
          calendars/Zoar.ics
          calendars/till-Bay.ics
