name: Manually Build Calendars

on: workflow_dispatch

jobs:
  build-calendars:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: BSFishy/pip-action@v1
      name: Pip install
      with:
        requirements: requirements.txt
    - uses: actions-rs/cargo@v1
      name: Cargo build
      with:
        command: build
        args: --release
    - uses: actions-rs/cargo@v1
      name: Cargo run
      with:
        command: run
        args: --release
    - uses: IsaacShelton/update-existing-release@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: calendars/*.ics
        release: Latest Eskom Loadshedding Calendars
        replace: true
        tag: v1.0.0
        body: "To get your loadshedding schedule in your calendar you should

          1. scroll down to the blue links under `Assets`

          2. Find the `ics` calendar file corresponding to your area

          3. Right-click on the file and copy the link

          4. Open your calendar app (Google Calendar, Outlook, Apple Calendar, etc)

          5. Paste the calendar link in your app's `subscribe to calendar` option.


          That's it! Now you've got loadshedding warning in your calendar that
          tell you if the power will be off or not. This is better than apps
          like EskomSePush because it combines what area you're in with your
          area's loadshedding schedule. 

          You'll only be notified if 


          1. there's national loadshedding announced by Eskom and 

          2. your area has loadshedding scheduled for that time.

          It's also open source! We depend on pull requests to update
          `manually_specified.yaml` with the latest schedule. Please submit a
          PR if Eskom announces a change!"
