name: Manually Build Calendars

on: workflow_dispatch

jobs:
  build-calendars:
    runs-on: ubuntu-latest
    steps:
    - name: Support longpaths
      run: git config --global core.longpaths true
    - uses: actions/checkout@v3
      name: Checkout repository
    - uses: BSFishy/pip-action@v1
      name: Pip install
      with:
        requirements: requirements.txt
    - uses: actions-rs/cargo@v1
      name: Cargo build
      with:
        command: build
        args: --release
    - uses: actions-rs/cargo@v1
      name: Cargo run
      with:
        command: run
        args: --release
    - name: Update latest release with new calendars
      uses: pyTooling/Actions/releaser@main
      with:
        tag: latest
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: calendars/*.*
