name: Build and Publish Calendars

on:
  push:
    branches: [ "main" ]
    paths:
      - 'manually_specified.yaml'
      - 'src/*.rs'
      - 'src/*.py'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-publish-calendars:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Pip install requirements
      uses: BSFishy/pip-action@v1
      with:
        requirements: requirements.txt

    - name: Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release

    - name: Cargo run
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: --release

    - name: Write current time stamp to GH variable
      id: date
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: List all calendars to GH variable
      run: echo "::set-output name=LS_CALENDARS::$(ls calendars/* | xargs echo | sed 's/ /,/g')"
      id: LS-CALENDARS

    - name: Update latest release with new calendars, retrying if needed
      uses: Wandalen/wretry.action@v1.0.11
      with:
        attempt_limit: 5    # Retry up to 5 times
        attempt_delay: 5000 # Wait 5 seconds between attempts
        action: beyarkay/update-existing-release@master
        with: |
          token: ${{ secrets.GH_ACTIONS_PAT }}
          release: Latest Eskom Loadshedding Calendars
          updateTag: true
          tag: latest
          replace: true
          body: "This is the body"
          files: ${{ steps.LS-CALENDARS.outputs.LS_CALENDARS }}
