name: Check python formatting with Black

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  fmt-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
